version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./db_data:/data/db

  criptos:
    build: ./criptos
    ports:
      - "3101:3001" 
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/criptoDB

  personas:
    build: ./persons
    ports:
      - "3102:3002"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/personasDB

  productos:
    build: ./productos
    ports:
      - "3103:3003"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/productosDB
    
  pets:
    build: ./pets
    ports:
      - "5100:5000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/petsDB

